### ISSUE TITLE
[PLAN] 引用分析任务服务开发

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#11]
完成引用分析任务任务服务开发。
现阶段不考虑其他因素，mock实体服务。

**Comment by HermitSun** [comment]
目前交给yzg一起完成。 @Tdycwym

**Comment by Tdycwym** [comment]
首先关于返回值，我想的是学者的返回一个List<String,List<String>>，就是每篇论文对应它引用的论文的ID的List，
然后论文的就直接返回一个List<String>

关于技术方面，我看了Spark的graphx，一个大数据的图处理框架，基本功能勉强会了，但是存在两个问题：
1.graphx需要每个实体对应一个long类型的ID。
2.graphx需要手动添加边集，就是说我还是要遍历一遍所有的Paper实体去获取Edge，可能效率只是和直接遍历差不多。

**Comment by HermitSun** [comment]
可以每天或者定时进行一次计算，数据总体来说还是比较稳定的，不容易发生频繁变更，主要考虑的还是读的性能。
下次看完之后会回复。

**Comment by HermitSun** [comment]
目前已初步完成。如果有问题，我会reopen这个issue。

**Comment by HermitSun** [comment]
我突然有一个问题，按照需求里的说法：
> 7.研究（者）引用关系分析
（1）论文引用其它论文及被其它论文引用情况
（2）**研究者引用其他研究者（的论文）及被其他研究者引用情况**
（3）评价研究（者）影响力
他这里的“研究者引用其他研究者（的论文）”，指的是查询研究者引用过的人的论文，还是研究者引用过的人，或者两者都是？

**Comment by HermitSun** [comment]
询问之后得到的结果：
> 按照你自己的理解能进行解释就行。按照文章逐条，也可以按照作者。或者返回两个研究者的引用关系。
你们怎么看？ @Tdycwym @NJUleo @Intrejan

**Comment by HermitSun** [comment]
目前暂时还是决定为学者和论文的引用关系分别提供一份接口，以应对未来的变更。
