### ISSUE TITLE
[PLAN] 影响力分析技术初步考察

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#4]
完成影响力分析的初步考察。

**Comment by Tdycwym** [comment]
学者的影响力主要考虑以下内容：
1.发布的论文数量：由于可能存在低质量的论文，这个作为主要衡量标准不合适。
2.发布的论文的影响力：从三个方面考虑：
    a.领域的特性：由于我们的领域是确定的，这个可以不计入计算范围。
    b.publisher：不同领域对应不同的影响因子，有现成的数据可以取用。
    c.与其他论文的引用关系：可以通过PageRank算法计算出一个指标。

然后论文的影响力显然不能直接求和作为作者的影响力，可以按照2.c.作出分级，比如A级*0.8 B级*0.5这样进行加权，最后得出一个数值来衡量学者的影响力。

**Comment by HermitSun** [comment]
也许可以有一个比较有效的获取引用关系的算法？这个可能还需要和zz配合 @NJUleo

**Comment by Tdycwym** [comment]
考虑到自定义算法的可行性问题，可以采用h指数，g指数等，直接作为衡量学者影响力的标准。

**Comment by HermitSun** [comment]
那目前阶段暂定先使用这两个指标中的一个（比较后再做决定）。
后续如果还有别的更好的思路，大家可以在讨论；我会reopen这个issue。

**Comment by HermitSun** [comment]
由于缺少评判论文影响力的计算方法，我reopen这个issue。
最好能有明确的计算方法 @Tdycwym

**Comment by Tdycwym** [comment]
暂时没有想到合适的计算方法，先用被引次数作为衡量的标准，如果有更合适的方法再进行修改。

**Comment by Tdycwym** [comment]
考虑了一下，可以获取到的比较直接的数据就是被引次数和影响因子，通过引用关系分析影响力的方法暂时没有找到。暂定被引次数*影响因子作为影响力。可以根据领域内的具体数据考虑调整参数或公式。

**Comment by HermitSun** [comment]
OK，暂时先这么处理。如果有其他问题，我会reopen这个issue。
