### ISSUE TITLE
[PLAN] 审稿人推荐技术初步考察

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#5]
完成审稿人推荐技术的初步考察。

**Comment by Intrejan** [comment]
审稿人推荐的意义在于推荐最能理解投稿论文的学者。
我认为推荐的学者应当满足以下条件：
1、专业领域和稿件涉及内容密切相关
2、仍在继续从事相关科研工作

按照优先级从高到低，审稿人推荐可以采用以下方式：
1、投稿论文中参考文献的作者。从投稿论文中参考文献的中，找出符合上述条件的作者。选择依据可以为【与投稿论文内容最直接相关的文章作者】或者【出现次数较多的作者】。这些作者往往与投稿论文研究方向密切相关。
2、通过数据库寻找到与投稿论文相关的作者。考虑到【投稿人撰写论文期间可能遗漏相关文章】，或者在【写作论文期间有新发表的论文】，通过数据库寻找内容相关文章作者可以作为补充。
3、投稿期刊发表的相关文章作者。这类作者便于期刊编辑联系或者与期刊有过合作，尤其是【如果这些作者出现在投稿论文的引用文献中】，对于推荐审稿人来说是相对较好的选择。
4、向学术会议交流提供过相关文章的作者。如果投稿论文将要参加学术会议，那么这类作者作为推荐审稿人则较为合适。

审稿人推荐还可能存在以下问题：
1、由于本系统只是负责推荐审稿人的可能人选，是否采用将有投稿人决定，因此考虑系统推荐审稿人候选时是否应该以作者影响力优先。因为事实上大专家并非审稿人的最佳人选，与投稿期刊水平相当的作者通常被认为是比较合适的选择。
2、由于系统无法对学者论文观点进行提取和归纳，因此为了避免推荐的审稿人候选与投稿人在学术观点上存在冲突，考虑系统是否应该提供给投稿人自行判断审稿人候选的服务，例如提供最相关论文链接等。

具体推荐方式，服务需要的参数和调用其他服务细节暂时未考虑。

**Comment by HermitSun** [comment]
按照要求，理想情况下也许是应该半自动地完成这个事情的。比如推荐的审稿人是否与投稿人在学术观点上存在冲突，这个如果能做成一个服务，然后自动判断这两个人是否存在冲突，肯定是最好的；如果不能，最好也能够分析出一个学者（在这个领域）的学术观点，然后再交给投稿人或者其他什么人去参考。
直接提供论文不是不行，只是可以再进一步，进一步提高自动化的程度。参考软工三被diss的经历……

**Comment by HermitSun** [comment]
目前主要是获取一个思路。
后续在执行过程中遇到问题，我会reopen这个issue，到时候继续讨论。

**Comment by HermitSun** [comment]
由于情况发生了变化，我reopen这个issue。

**Comment by Intrejan** [comment]
经过与老师的交流，决定提供推荐和不推荐两份审稿人候选名单，其中不推荐名单在当前阶段通过【曾经合作过的作者】，和【研究领域无重合作者】条件来进行筛选。审稿人目前考虑均按照影响力进行排序。

**Comment by HermitSun** [comment]
OK，目前暂时采用这个方案。如果后面还有问题，会reopen这个issue。
