### ISSUE TITLE
[BUG] 引用分析服务无法通过单元测试

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#59]
## 错误表现

`testGetResearcherQuoted`和`testGetResearcherQuoting`无法通过单元测试

https://github.com/NJU-SE-17-advanced-se/backend/actions/runs/350864495

## 预期行为

应该通过单元测试

## 执行环境

java 1.8，maven 3.6.3

## 复现步骤

`mvn test`

**Comment by Tdycwym** [comment]
由于新增的判断学者实体服务返回值是否为空学者，而Mock的学者实体未修改而产生错误，现已解决。
