### ISSUE TITLE
[PLAN] 合作关系分析与预测技术初步考察

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#7]
完成合作关系分析与预测的技术初步考察。

由于个人原因，下周到周五之前没有空余时间，不一定能完成，故安排到 Sprint 2。

**Comment by HermitSun** [comment]
阅读唐杰的相关论文，搜寻资料。
并且之前似乎有用到过相关技术，我去问问。

**Comment by HermitSun** [comment]
@Intrejan 可以在这里写一下看论文的结果

**Comment by Intrejan** [comment]
关于合作关系分析，采用的是基于合著与共引关系的学者关联度模型，首先合著能够体现作者之间直接的合作关系，对于合作关系分析是有意义的；其次，共引论文越多，意味着研究方向的相似程度越高，作者引用耦合反映了作者间隐含的联系。因此采用合著和共引作为学者关联程度的分析依据。

**Comment by Intrejan** [comment]
关于合作关系预测，论文介绍的模型比价复杂，初步考虑想采用的是与作者有合著和共引关系的作者作为全集；按照作者学术影响力，作者研究领域重合度，以及作者在合作关系网络中的影响力3个方面加权和作为合作推荐度的指标。（论文中的每一项评分的权值未给出具体数值，可能要自己设定）

**Comment by HermitSun** [comment]
目前按照这个内容进行开发。后面如果有问题，我会reopen这个issue。
