### ISSUE TITLE
[PLAN] 影响力分析任务服务开发

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#8]
完成影响力分析任务服务开发。
现阶段不考虑其他因素，mock实体服务。

**Comment by HermitSun** [comment]
麻烦统计一下在编写影响力分析服务过程用到的实体服务，以及调用的实体服务的方法。

**Comment by Tdycwym** [comment]
ScholarVo（学者）、PaperVo（论文）

**Comment by HermitSun** [comment]
目前已完成一阶段开发。暂时close。

**Comment by HermitSun** [comment]
我在集成的时候发现影响力分析这块的接口不太对劲。具体内容如下：

https://github.com/NJU-SE-17-advanced-se/backend/blob/5f1d94480dbccba44d91394f542e5e4467facccb/task-impact-analysis/src/main/java/org/njuse17advancedse/taskimpactanalysis/controller/TaskImpactAnalysisController.java#L13-L23

这个接口不应当把学者和论文的内容混为一谈，我觉得应该分成两个接口。
上次review的时候可能是因为同时推送了两个服务，导致交流的时候出现了偏差。 @Tdycwym

**Comment by HermitSun** [comment]
目前已经完成了调整。暂时close。
