### ISSUE TITLE
[PLAN] 审稿人推荐任务服务开发

### ISSUE THREAD

**Issue by HermitSun** [NJU-SE-17-advanced-se/backend#9]
完成审稿人推荐任务服务开发。
现阶段不考虑其他因素，mock实体服务。

**Comment by HermitSun** [comment]
讨论之后觉得审稿人推荐功能应该是针对**新论文**的，而非已有的论文。
不过就算是新论文，也应当分配一个id。
需要增加一个上传论文的接口。

**Comment by Intrejan** [comment]
经过讨论暂且决定不推荐审稿人从【研究方向相关】并且【与投稿人有较为密切合作】的作者中产生，取前5个作者。

**Comment by HermitSun** [comment]
现阶段任务已经完成。后续如果有变化，我会reopen这个issue。
